apiVersion: v1
data:
  MYSQL_DATABASE: Z3JlZXRlcg==
  MYSQL_PASSWORD: Z3JlZXRlcg==
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
  MYSQL_ROOT_USER: cm9vdA==
  MYSQL_USER: Z3JlZXRlcg==
kind: Secret
metadata:
  labels:
    app: database
  name: database-secret
type: string
