FROM nginxinc/nginx-unprivileged:stable

ADD android-chrome-192x192.png /usr/share/nginx/html/
ADD android-chrome-512x512.png /usr/share/nginx/html/
ADD apple-touch-icon.png /usr/share/nginx/html/
ADD favicon-16x16.png /usr/share/nginx/html/
ADD favicon-32x32.png /usr/share/nginx/html/
ADD favicon.ico /usr/share/nginx/html/
ADD site.webmanifest /usr/share/nginx/html/
